import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/header/page";
import Footer from "../components/footer/page";
import Navbar from "../components/navbar/page";
import styles from './layout.module.scss'


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "수수 블로그",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("IN RootLayout", children)
  return (
    <html className={styles.html} >
      <body className={styles.layoutContainer}>
      <Header />
        <div className={styles.headerContainer}>   
        <Navbar />
        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
