import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/header/page";
import Footer from "../components/footer/page";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "수수 블로그",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("IN RootLayout")
  return (
    <html>
    <Header />
      <body className={inter.className}>{children}</body>
    <Footer />
    </html>
  );
}
